/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signup */
        post: operations["signup_api_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/consent/ocr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Consent Ocr */
        post: operations["consent_ocr_api_auth_consent_ocr_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Me */
        get: operations["export_me_api_me_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Me */
        delete: operations["delete_me_api_me_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Portfolios */
        get: operations["get_portfolios_api_portfolios_get"];
        put?: never;
        /** Create Portfolio */
        post: operations["create_portfolio_api_portfolios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/combined/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Combined Summary */
        get: operations["combined_summary_api_portfolios_combined_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get One */
        get: operations["get_one_api_portfolios__portfolio_id__get"];
        put?: never;
        post?: never;
        /** Delete Portfolio */
        delete: operations["delete_portfolio_api_portfolios__portfolio_id__delete"];
        options?: never;
        head?: never;
        /** Patch Portfolio */
        patch: operations["patch_portfolio_api_portfolios__portfolio_id__patch"];
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_api_portfolios__portfolio_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/holdings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Holdings */
        get: operations["holdings_api_portfolios__portfolio_id__holdings_get"];
        put?: never;
        /** Add Holding */
        post: operations["add_holding_api_portfolios__portfolio_id__holdings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/xray": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Xray */
        get: operations["xray_api_portfolios__portfolio_id__xray_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/heatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Heatmap */
        get: operations["heatmap_api_portfolios__portfolio_id__heatmap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/holdings/{holding_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Holding */
        delete: operations["delete_holding_api_portfolios__portfolio_id__holdings__holding_id__delete"];
        options?: never;
        head?: never;
        /** Patch Holding */
        patch: operations["patch_holding_api_portfolios__portfolio_id__holdings__holding_id__patch"];
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Import */
        post: operations["create_import_api_portfolios__portfolio_id__imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports/{draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Import */
        get: operations["get_import_api_imports__draft_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Import */
        patch: operations["patch_import_api_imports__draft_id__patch"];
        trace?: never;
    };
    "/api/imports/{draft_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Import */
        post: operations["confirm_import_api_imports__draft_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/risk/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Risk Presets */
        get: operations["risk_presets_api_risk_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/securities/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Securities Search */
        get: operations["securities_search_api_securities_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/holdings/{holding_id}/scorecard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scorecard */
        get: operations["scorecard_api_holdings__holding_id__scorecard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alerts */
        get: operations["alerts_api_alerts_get"];
        put?: never;
        /** Create Alert */
        post: operations["create_alert_api_alerts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{alert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Alert */
        delete: operations["delete_alert_api_alerts__alert_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Notifications */
        get: operations["notifications_api_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Read Notification */
        post: operations["read_notification_api_notifications__notification_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertCreate */
        AlertCreate: {
            /** Symbol */
            symbol: string;
            /**
             * Op
             * @enum {string}
             */
            op: "above" | "below";
            /** Price */
            price: number;
        };
        /** AlertOut */
        AlertOut: {
            /** Id */
            id: number;
            /** Symbol */
            symbol: string;
            /** Op */
            op: string;
            /** Price */
            price: number;
            /** Active */
            active: boolean;
            /** Triggered At */
            triggered_at?: string | null;
        };
        /** Body_create_import_api_portfolios__portfolio_id__imports_post */
        Body_create_import_api_portfolios__portfolio_id__imports_post: {
            /** File */
            file: string;
        };
        /** Breach */
        Breach: {
            /** Rule */
            rule: string;
            /** Value */
            value: number;
            /** Limit */
            limit: number;
            /** Why */
            why: string;
            /** Symbol */
            symbol?: string | null;
        };
        /** ExposureItem */
        ExposureItem: {
            /** Name */
            name: string;
            /** Weight Pct */
            weight_pct: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeatmapItem */
        HeatmapItem: {
            /** Symbol */
            symbol: string;
            /** Sector */
            sector: string;
            /** Weight Pct */
            weight_pct: number;
            /** Day Change Pct */
            day_change_pct: number;
        };
        /** HoldingCreate */
        HoldingCreate: {
            /** Symbol */
            symbol: string;
            /** Quantity */
            quantity: number;
            /** Avg Cost */
            avg_cost?: number | null;
            /** Cost Currency */
            cost_currency?: ("ILS" | "USD") | null;
            /** Horizon */
            horizon?: ("1w" | "1m" | "3m" | "6m" | "1y") | null;
        };
        /** HoldingOut */
        HoldingOut: {
            /** Id */
            id: number;
            /** Symbol */
            symbol: string;
            /** Name En */
            name_en: string;
            /** Name He */
            name_he: string;
            /** Asset Type */
            asset_type: string;
            /** Market */
            market: string;
            /** Quantity */
            quantity: number;
            /** Price */
            price: number;
            /** Currency */
            currency: string;
            /** Day Change Pct */
            day_change_pct: number;
            /** Value Ils */
            value_ils: number;
            pnl?: components["schemas"]["Pnl"] | null;
            /** Weight Pct */
            weight_pct: number;
            /** Horizon */
            horizon?: ("1w" | "1m" | "3m" | "6m" | "1y") | null;
            /**
             * Stop Tp Status
             * @enum {string}
             */
            stop_tp_status: "missing" | "needs_horizon";
            score_card: components["schemas"]["ScoreCardMini"];
            /**
             * Price Stale
             * @default false
             */
            price_stale: boolean;
        };
        /** HoldingPatch */
        HoldingPatch: {
            /** Quantity */
            quantity?: number | null;
            /** Avg Cost */
            avg_cost?: number | null;
            /** Cost Currency */
            cost_currency?: ("ILS" | "USD") | null;
            /** Horizon */
            horizon?: ("1w" | "1m" | "3m" | "6m" | "1y") | null;
            /** Risk Override */
            risk_override?: {
                [key: string]: unknown;
            } | null;
        };
        /** ImportDraftOut */
        ImportDraftOut: {
            /** Id */
            id: number;
            /** Portfolio Id */
            portfolio_id: number;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "confirmed" | "discarded";
            /** Rows */
            rows: components["schemas"]["ImportRowModel"][];
            /** Proposed Changes */
            proposed_changes: components["schemas"]["ProposedChange"][];
        };
        /** ImportPatch */
        ImportPatch: {
            /** Rows */
            rows?: components["schemas"]["ImportRowModel"][] | null;
            /** Proposed Changes */
            proposed_changes?: components["schemas"]["ProposedChange"][] | null;
        };
        /** ImportRowModel */
        ImportRowModel: {
            /**
             * Index
             * @default 0
             */
            index: number;
            /**
             * Name
             * @default
             */
            name: string;
            /** Symbol */
            symbol?: string | null;
            /** Tase Number */
            tase_number?: string | null;
            /** Quantity */
            quantity?: number | null;
            /** Price */
            price?: number | null;
            /** Value */
            value?: number | null;
            /** Cost */
            cost?: number | null;
            /**
             * Currency
             * @default ILS
             */
            currency: string;
            /**
             * Unit
             * @default ILS
             * @enum {string}
             */
            unit: "ILS" | "agorot" | "USD";
            /** Matched Name */
            matched_name?: string | null;
            /** Candidates */
            candidates?: components["schemas"]["MatchCandidate"][];
            /** Flags */
            flags?: ("missing_fields" | "value_mismatch" | "unmatched" | "low_confidence_match" | "currency_changed" | "unit_mismatch")[];
        };
        /** LoginIn */
        LoginIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MarketOpen */
        MarketOpen: {
            /** Open */
            open: boolean;
        };
        /** Markets */
        Markets: {
            US: components["schemas"]["MarketOpen"];
            TASE: components["schemas"]["MarketOpen"];
            CRYPTO: components["schemas"]["MarketOpen"];
        };
        /**
         * MatchCandidate
         * @description A possible security for a row whose name match was too weak to accept automatically.
         */
        MatchCandidate: {
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Score */
            score: number;
        };
        /** MeOut */
        MeOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Locale */
            locale: string;
            /** Disclaimer Accepted */
            disclaimer_accepted: boolean;
            /** Ocr Consent */
            ocr_consent: boolean;
            /** Csrf Token */
            csrf_token: string;
        };
        /** Money */
        Money: {
            /** Ils */
            ils: number;
            /** Usd */
            usd: number;
        };
        /** MonthlyBar */
        MonthlyBar: {
            /** Month */
            month: string;
            /** Pnl Ils */
            pnl_ils: number;
            /** Pct */
            pct: number;
        };
        /** NotificationOut */
        NotificationOut: {
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Read */
            read: boolean;
        };
        /** Pnl */
        Pnl: {
            /** Ils */
            ils: number;
            /** Usd */
            usd: number;
            /** Pct */
            pct: number;
        };
        /** PortfolioCreate */
        PortfolioCreate: {
            /** Name */
            name: string;
            /**
             * Base Currency
             * @default ILS
             * @enum {string}
             */
            base_currency: "ILS" | "USD";
        };
        /** PortfolioOut */
        PortfolioOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Base Currency */
            base_currency: string;
            risk_filter: components["schemas"]["RiskFilterOut"];
            /** Tracking Started At */
            tracking_started_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PortfolioPatch */
        PortfolioPatch: {
            /** Name */
            name?: string | null;
            /** Base Currency */
            base_currency?: ("ILS" | "USD") | null;
            /** Risk Filter */
            risk_filter?: {
                [key: string]: unknown;
            } | null;
        };
        /** ProposedChange */
        ProposedChange: {
            /** Row Index */
            row_index: number;
            /** Symbol */
            symbol: string | null;
            /**
             * Type
             * @enum {string}
             */
            type: "buy" | "sell" | "deposit" | "withdrawal";
            /** Quantity */
            quantity: number | null;
            /** Amount */
            amount: number | null;
            /** Currency */
            currency: string;
        };
        /** RiskFilterOut */
        RiskFilterOut: {
            /** Preset */
            preset?: string | null;
            /** Max Position Pct */
            max_position_pct: number;
            /** Max Sector Pct */
            max_sector_pct: number;
            /** Max Country Pct */
            max_country_pct: number;
            /** Max Loss Per Position Pct */
            max_loss_per_position_pct: number;
            /** Max Portfolio Risk Per Trade Pct */
            max_portfolio_risk_per_trade_pct: number;
            /** Max Total Portfolio Risk Pct */
            max_total_portfolio_risk_pct: number;
            /** Min Rr */
            min_rr: number;
            /**
             * Stop Type
             * @enum {string}
             */
            stop_type: "fixed" | "trailing" | "both";
            /** Drawdown Defensive Pct */
            drawdown_defensive_pct: number;
        };
        /** RiskPresetOut */
        RiskPresetOut: {
            /** Preset */
            preset?: string | null;
            /** Max Position Pct */
            max_position_pct: number;
            /** Max Sector Pct */
            max_sector_pct: number;
            /** Max Country Pct */
            max_country_pct: number;
            /** Max Loss Per Position Pct */
            max_loss_per_position_pct: number;
            /** Max Portfolio Risk Per Trade Pct */
            max_portfolio_risk_per_trade_pct: number;
            /** Max Total Portfolio Risk Pct */
            max_total_portfolio_risk_pct: number;
            /** Min Rr */
            min_rr: number;
            /**
             * Stop Type
             * @enum {string}
             */
            stop_type: "fixed" | "trailing" | "both";
            /** Drawdown Defensive Pct */
            drawdown_defensive_pct: number;
            /** Name */
            name: string;
        };
        /** ScoreCardDetail */
        ScoreCardDetail: {
            /** Holding Id */
            holding_id: number;
            /** Portfolio Id */
            portfolio_id: number;
            /** Symbol */
            symbol: string;
            /** Name En */
            name_en: string;
            /** Name He */
            name_he: string;
            /** Horizon */
            horizon?: ("1w" | "1m" | "3m" | "6m" | "1y") | null;
            /** Total */
            total: number;
            /** Confidence */
            confidence: number;
            /** Available */
            available: boolean;
            /** Validated */
            validated: boolean;
            /** Signals */
            signals: components["schemas"]["SignalBreakdownOut"][];
            /** Explanation */
            explanation: {
                [key: string]: unknown;
            };
            /** Disclaimer */
            disclaimer: string;
        };
        /** ScoreCardMini */
        ScoreCardMini: {
            /** Total */
            total: number;
            /** Technical */
            technical: number;
            /** Patterns */
            patterns: number;
            /** Confidence */
            confidence: number;
        };
        /** SecurityHit */
        SecurityHit: {
            /** Symbol */
            symbol: string;
            /** Name En */
            name_en: string;
            /** Name He */
            name_he: string;
            /** Market */
            market: string;
        };
        /** SeriesPoint */
        SeriesPoint: {
            /** Date */
            date: string;
            /** Pct */
            pct: number;
            /** Sp500 Pct */
            sp500_pct?: number | null;
            /** Ta125 Pct */
            ta125_pct?: number | null;
        };
        /** SignalBreakdownOut */
        SignalBreakdownOut: {
            /** Name */
            name: string;
            /** Score */
            score: number;
            /** Confidence */
            confidence: number;
            /** Weight */
            weight: number;
            /** Nominal Weight */
            nominal_weight?: number | null;
            /** Reasons */
            reasons: string[];
            /** Data As Of */
            data_as_of: string;
            /** Explanation */
            explanation: {
                [key: string]: unknown;
            };
        };
        /** SignupIn */
        SignupIn: {
            /** Invite Code */
            invite_code: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Accept Disclaimer */
            accept_disclaimer: boolean;
            /**
             * Locale
             * @default he
             * @enum {string}
             */
            locale: "he" | "en";
        };
        /** SummaryOut */
        SummaryOut: {
            value: components["schemas"]["Money"];
            day_pnl: components["schemas"]["Pnl"];
            week_pnl: components["schemas"]["Pnl"];
            month_pnl: components["schemas"]["Pnl"];
            since_start_pnl: components["schemas"]["Pnl"];
            /** Since Start Date */
            since_start_date?: string | null;
            /**
             * Week Start
             * Format: date
             */
            week_start: string;
            /** Fx Stale */
            fx_stale: boolean;
            /** Weekly Bars */
            weekly_bars: components["schemas"]["WeeklyBar"][];
            /** Monthly Bars */
            monthly_bars: components["schemas"]["MonthlyBar"][];
            /** Since Start Series */
            since_start_series: components["schemas"]["SeriesPoint"][];
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            markets: components["schemas"]["Markets"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeeklyBar */
        WeeklyBar: {
            /**
             * Week Start
             * Format: date
             */
            week_start: string;
            /** Pnl Ils */
            pnl_ils: number;
            /** Pct */
            pct: number;
        };
        /** XrayOut */
        XrayOut: {
            /** Concentration */
            concentration: {
                [key: string]: unknown;
            }[];
            /** Currency Exposure */
            currency_exposure: components["schemas"]["ExposureItem"][];
            /** Country Exposure */
            country_exposure: components["schemas"]["ExposureItem"][];
            /** Sector Exposure */
            sector_exposure: components["schemas"]["ExposureItem"][];
            /** Home Bias */
            home_bias: {
                [key: string]: unknown;
            };
            /** Breaches */
            breaches: components["schemas"]["Breach"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signup_api_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    consent_ocr_api_auth_consent_ocr_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    export_me_api_me_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    delete_me_api_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_portfolios_api_portfolios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioOut"][];
                };
            };
        };
    };
    create_portfolio_api_portfolios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    combined_summary_api_portfolios_combined_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryOut"];
                };
            };
        };
    };
    get_one_api_portfolios__portfolio_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_portfolio_api_portfolios__portfolio_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_portfolio_api_portfolios__portfolio_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_api_portfolios__portfolio_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    holdings_api_portfolios__portfolio_id__holdings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_holding_api_portfolios__portfolio_id__holdings_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    xray_api_portfolios__portfolio_id__xray_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["XrayOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    heatmap_api_portfolios__portfolio_id__heatmap_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeatmapItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_holding_api_portfolios__portfolio_id__holdings__holding_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
                holding_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_holding_api_portfolios__portfolio_id__holdings__holding_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
                holding_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldingPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_import_api_portfolios__portfolio_id__imports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_import_api_portfolios__portfolio_id__imports_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportDraftOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_import_api_imports__draft_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportDraftOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_import_api_imports__draft_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportDraftOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_import_api_imports__draft_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportDraftOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    risk_presets_api_risk_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskPresetOut"][];
                };
            };
        };
    };
    securities_search_api_securities_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecurityHit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scorecard_api_holdings__holding_id__scorecard_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                holding_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreCardDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alerts_api_alerts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"][];
                };
            };
        };
    };
    create_alert_api_alerts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_alert_api_alerts__alert_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    notifications_api_notifications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationOut"][];
                };
            };
        };
    };
    read_notification_api_notifications__notification_id__read_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
