/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signup */
        post: operations["signup_api_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/consent/ocr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Consent Ocr */
        post: operations["consent_ocr_api_auth_consent_ocr_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Me */
        post: operations["export_me_api_me_export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Me */
        delete: operations["delete_me_api_me_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_auth_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Session */
        delete: operations["revoke_session_api_auth_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sessions/revoke-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke All Sessions
         * @description Log out everywhere else: every session of this user except the current one.
         *
         *     Other browsers also lose their "known device" status (new nonce); this one keeps it.
         */
        post: operations["revoke_all_sessions_api_auth_sessions_revoke_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Portfolios */
        get: operations["get_portfolios_api_portfolios_get"];
        put?: never;
        /** Create Portfolio */
        post: operations["create_portfolio_api_portfolios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/combined/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Combined Summary */
        get: operations["combined_summary_api_portfolios_combined_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get One */
        get: operations["get_one_api_portfolios__portfolio_id__get"];
        put?: never;
        post?: never;
        /** Delete Portfolio */
        delete: operations["delete_portfolio_api_portfolios__portfolio_id__delete"];
        options?: never;
        head?: never;
        /** Patch Portfolio */
        patch: operations["patch_portfolio_api_portfolios__portfolio_id__patch"];
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_api_portfolios__portfolio_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/holdings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Holdings */
        get: operations["holdings_api_portfolios__portfolio_id__holdings_get"];
        put?: never;
        /** Add Holding */
        post: operations["add_holding_api_portfolios__portfolio_id__holdings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/xray": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Xray */
        get: operations["xray_api_portfolios__portfolio_id__xray_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/heatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Heatmap */
        get: operations["heatmap_api_portfolios__portfolio_id__heatmap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/holdings/{holding_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Holding */
        delete: operations["delete_holding_api_portfolios__portfolio_id__holdings__holding_id__delete"];
        options?: never;
        head?: never;
        /** Patch Holding */
        patch: operations["patch_holding_api_portfolios__portfolio_id__holdings__holding_id__patch"];
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Import */
        post: operations["create_import_api_portfolios__portfolio_id__imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/imports/rows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Import From Rows
         * @description On-device OCR path: no image ever reaches the server. No OCR consent is needed (no third
         *     party and no server-side reading).
         */
        post: operations["create_import_from_rows_api_portfolios__portfolio_id__imports_rows_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports/{draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Import */
        get: operations["get_import_api_imports__draft_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Import */
        patch: operations["patch_import_api_imports__draft_id__patch"];
        trace?: never;
    };
    "/api/imports/{draft_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Import */
        post: operations["confirm_import_api_imports__draft_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/launch-gate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Launch Gate
         * @description Whether live buy/sell verdicts may be served, and if not, why not.
         */
        get: operations["launch_gate_api_launch_gate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/risk/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Risk Presets */
        get: operations["risk_presets_api_risk_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/securities/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Securities Search
         * @description Seeded or provider-verified securities only (never another user's unverified ticker).
         */
        get: operations["securities_search_api_securities_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/holdings/{holding_id}/scorecard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scorecard */
        get: operations["scorecard_api_holdings__holding_id__scorecard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alerts */
        get: operations["alerts_api_alerts_get"];
        put?: never;
        /** Create Alert */
        post: operations["create_alert_api_alerts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{alert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Alert */
        delete: operations["delete_alert_api_alerts__alert_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Notifications */
        get: operations["notifications_api_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Read Notification */
        post: operations["read_notification_api_notifications__notification_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/holdings/{holding_id}/exit-levels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Holding Exit Levels
         * @description Stop / take-profit levels. `horizon` overrides the holding's own (a what-if, not saved); a
         *     holding with no horizon and no override answers `needs_horizon`. `risk` is a preset name.
         */
        get: operations["holding_exit_levels_api_holdings__holding_id__exit_levels_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/exit-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exit Review
         * @description Levels for every holding plus portfolio totals: the total risk to the stops, the biggest
         *     contributors, the positions with no stop and stops that look too tight or too wide.
         */
        post: operations["exit_review_api_portfolios__portfolio_id__exit_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertCreate */
        AlertCreate: {
            /** Symbol */
            symbol: string;
            /**
             * Op
             * @enum {string}
             */
            op: "above" | "below";
            /** Price */
            price: number;
        };
        /** AlertOut */
        AlertOut: {
            /** Id */
            id: number;
            /** Symbol */
            symbol: string;
            /**
             * Op
             * @enum {string}
             */
            op: "above" | "below";
            /** Price */
            price: number;
            /** Active */
            active: boolean;
            /** Triggered At */
            triggered_at?: string | null;
        };
        /** AnalystTargetsIn */
        AnalystTargetsIn: {
            /** Mean */
            mean?: number | null;
            /** High */
            high?: number | null;
        };
        /** Breach */
        Breach: {
            /** Rule */
            rule: string;
            /** Value */
            value: number;
            /** Limit */
            limit: number;
            /** Why */
            why: string;
            /** Symbol */
            symbol?: string | null;
        };
        /**
         * ChallengeRequiredOut
         * @description 403 body of `POST /auth/login` when a Cloudflare Turnstile token is needed.
         */
        ChallengeRequiredOut: {
            /** Detail */
            detail: string;
            /**
             * Code
             * @constant
             */
            code: "turnstile_required";
            /** Site Key */
            site_key?: string | null;
        };
        /**
         * ChartAnnotation
         * @description Something the chart should draw: a level, a moving average or a detected pattern.
         */
        ChartAnnotation: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "support" | "resistance" | "moving_average" | "pattern";
            /** Label */
            label: string;
            /** Price */
            price?: number | null;
            /** As Of */
            as_of?: string | null;
        };
        /** ExitLevel */
        ExitLevel: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "stop" | "trailing_stop" | "breakeven" | "take_profit";
            /** Label */
            label: string;
            /** Price */
            price: number;
            /** Distance Pct */
            distance_pct: number;
            /** Vs Price Ils */
            vs_price_ils: number;
            /** Vs Price Usd */
            vs_price_usd: number;
            /** Pnl Native */
            pnl_native?: number | null;
            /** Pnl Ils */
            pnl_ils?: number | null;
            /** Pnl Usd */
            pnl_usd?: number | null;
            /** Rr */
            rr?: number | null;
            /**
             * Reached
             * @default false
             */
            reached: boolean;
            /** Source */
            source: string;
            /** Reason */
            reason: string;
            explanation: components["schemas"]["Explanation"];
        };
        /** ExitLevelsResult */
        ExitLevelsResult: {
            /**
             * Status
             * @enum {string}
             */
            status: "levels" | "needs_horizon" | "no_levels";
            /** Reason Code */
            reason_code?: ("needs_horizon" | "stale_price" | "no_history" | "insufficient_history" | "history_price_mismatch") | null;
            /** Reason */
            reason: string;
            /** Symbol */
            symbol: string;
            horizon?: components["schemas"]["Horizon"] | null;
            /** Horizon Label */
            horizon_label?: string | null;
            /** Risk Preset */
            risk_preset?: string | null;
            /** Currency */
            currency?: string | null;
            /** Price */
            price?: number | null;
            /** Price As Of */
            price_as_of?: string | null;
            /** Atr */
            atr?: number | null;
            /** Atr Timeframe */
            atr_timeframe?: string | null;
            stop?: components["schemas"]["ExitLevel"] | null;
            trailing_stop?: components["schemas"]["ExitLevel"] | null;
            breakeven?: components["schemas"]["ExitLevel"] | null;
            /** Take Profits */
            take_profits?: components["schemas"]["ExitLevel"][];
            /** Scale Out */
            scale_out?: components["schemas"]["ScaleOutStep"][];
            size_guidance?: components["schemas"]["SizeGuidance"] | null;
            risk_to_stop?: components["schemas"]["RiskToStop"] | null;
            /** Stop Fit */
            stop_fit?: ("ok" | "too_tight" | "too_wide") | null;
            /** Candidates */
            candidates?: components["schemas"]["StopCandidate"][];
            /** Skipped */
            skipped?: components["schemas"]["SkippedSource"][];
            state?: components["schemas"]["StopState"] | null;
            explanation: components["schemas"]["Explanation"];
            /**
             * Disclaimer
             * @default Not financial advice.
             */
            disclaimer: string;
        };
        /**
         * ExitReviewIn
         * @description A what-if: `horizon` / `risk` override every holding's own for this review only.
         */
        ExitReviewIn: {
            /** Horizon */
            horizon?: ("1w" | "1m" | "3m" | "6m" | "1y") | null;
            /** Risk */
            risk?: ("very_conservative" | "conservative" | "balanced" | "balanced_aggressive" | "aggressive" | "very_aggressive") | null;
            /** Prior Stops */
            prior_stops?: {
                [key: string]: number;
            };
            /** Analyst Targets */
            analyst_targets?: {
                [key: string]: components["schemas"]["AnalystTargetsIn"];
            };
        };
        /** ExitReviewOut */
        ExitReviewOut: {
            /** Portfolio Id */
            portfolio_id: number;
            /** Portfolio Value Ils */
            portfolio_value_ils: number;
            /** Rows */
            rows: components["schemas"]["ReviewRow"][];
            totals: components["schemas"]["ReviewTotals"];
            /**
             * Disclaimer
             * @default Not financial advice.
             */
            disclaimer: string;
        };
        /**
         * Explanation
         * @description The "Why?" of a scored object (CLAUDE.md shape), versioned and stored with it.
         *
         *     `summary`, `inputs` and `rules_applied` are the v0 fields the frontend already reads; they stay
         *     as part of v1. Every field after them has a default, so payloads cached before v1 still load.
         */
        Explanation: {
            /**
             * Version
             * @default 1
             */
            version: number;
            /** Summary */
            summary: string;
            /** Inputs */
            inputs?: {
                [key: string]: number | string;
            };
            /** Rules Applied */
            rules_applied?: string[];
            /** As Of */
            as_of?: string | null;
            /** Contributions */
            contributions?: components["schemas"]["SignalContribution"][];
            /** Annotations */
            annotations?: components["schemas"]["ChartAnnotation"][];
            /** Risk Rules Applied */
            risk_rules_applied?: string[];
            /** Invalidation Risks */
            invalidation_risks?: string[];
            /** Sources */
            sources?: components["schemas"]["ExplanationSource"][];
        };
        /**
         * ExplanationSource
         * @description Where a number came from and how fresh it is.
         */
        ExplanationSource: {
            /** Name */
            name: string;
            /** As Of */
            as_of?: string | null;
            /**
             * Detail
             * @default
             */
            detail: string;
        };
        /** ExposureItem */
        ExposureItem: {
            /** Name */
            name: string;
            /** Weight Pct */
            weight_pct: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /**
             * Scheduler
             * @enum {string}
             */
            scheduler: "leader" | "standby" | "unavailable" | "external";
            /** Leader */
            leader: boolean;
            /** Last Quotes At */
            last_quotes_at: string | null;
            /** Last Snapshot At */
            last_snapshot_at: string | null;
        };
        /** HeatmapItem */
        HeatmapItem: {
            /** Symbol */
            symbol: string;
            /** Sector */
            sector: string;
            /** Weight Pct */
            weight_pct: number;
            /** Day Change Pct */
            day_change_pct: number;
        };
        /** HoldingCreate */
        HoldingCreate: {
            /** Symbol */
            symbol: string;
            /** Quantity */
            quantity: number;
            /** Avg Cost */
            avg_cost?: number | null;
            /** Cost Currency */
            cost_currency?: ("ILS" | "USD") | null;
            /** Horizon */
            horizon?: ("1w" | "1m" | "3m" | "6m" | "1y") | null;
        };
        /** HoldingOut */
        HoldingOut: {
            /** Id */
            id: number;
            /** Symbol */
            symbol: string;
            /** Name En */
            name_en: string;
            /** Name He */
            name_he: string;
            /**
             * Asset Type
             * @enum {string}
             */
            asset_type: "stock" | "etf" | "crypto" | "fund" | "bond" | "cash";
            /**
             * Market
             * @enum {string}
             */
            market: "US" | "TASE" | "CRYPTO";
            /** Quantity */
            quantity: number;
            /** Price */
            price: number;
            /** Currency */
            currency: string;
            /** Day Change Pct */
            day_change_pct: number;
            /** Value Ils */
            value_ils: number;
            pnl?: components["schemas"]["Pnl"] | null;
            /** Weight Pct */
            weight_pct: number;
            /** Horizon */
            horizon?: ("1w" | "1m" | "3m" | "6m" | "1y") | null;
            /**
             * Stop Tp Status
             * @enum {string}
             */
            stop_tp_status: "missing" | "needs_horizon";
            score_card: components["schemas"]["ScoreCardMini"];
            /**
             * Price Stale
             * @default false
             */
            price_stale: boolean;
            /** Price Source */
            price_source?: string | null;
            /**
             * Price Basis
             * @default live
             * @enum {string}
             */
            price_basis: "live" | "last_close";
            /** Price As Of */
            price_as_of?: string | null;
            /**
             * Price Is Fresh
             * @default false
             */
            price_is_fresh: boolean;
            /** Price Flag */
            price_flag?: string | null;
        };
        /** HoldingPatch */
        HoldingPatch: {
            /** Quantity */
            quantity?: number | null;
            /** Avg Cost */
            avg_cost?: number | null;
            /** Cost Currency */
            cost_currency?: ("ILS" | "USD") | null;
            /** Horizon */
            horizon?: ("1w" | "1m" | "3m" | "6m" | "1y") | null;
            risk_override?: components["schemas"]["RiskOverride"] | null;
        };
        /**
         * Horizon
         * @enum {string}
         */
        Horizon: "1w" | "1m" | "3m" | "6m" | "1y";
        /** ImportDraftOut */
        ImportDraftOut: {
            /** Id */
            id: number;
            /** Portfolio Id */
            portfolio_id: number;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "confirmed" | "discarded";
            /**
             * Scope
             * @default partial
             * @enum {string}
             */
            scope: "partial" | "full";
            /** Rows */
            rows: components["schemas"]["ImportRowModel"][];
            /** Proposed Changes */
            proposed_changes: components["schemas"]["ProposedChange"][];
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** ImportPatch */
        ImportPatch: {
            /** Rows */
            rows?: components["schemas"]["ImportRowModel"][] | null;
            /** Proposed Changes */
            proposed_changes?: components["schemas"]["ProposedChange"][] | null;
            /** Scope */
            scope?: ("partial" | "full") | null;
        };
        /** ImportRowModel */
        ImportRowModel: {
            /**
             * Index
             * @default 0
             */
            index: number;
            /**
             * Name
             * @default
             */
            name: string;
            /** Symbol */
            symbol?: string | null;
            /** Tase Number */
            tase_number?: string | null;
            /** Quantity */
            quantity?: number | null;
            /** Price */
            price?: number | null;
            /** Value */
            value?: number | null;
            /** Cost */
            cost?: number | null;
            /**
             * Currency
             * @default ILS
             * @enum {string}
             */
            currency: "ILS" | "USD";
            /**
             * Unit
             * @default ILS
             * @enum {string}
             */
            unit: "ILS" | "agorot" | "USD";
            /** Matched Name */
            matched_name?: string | null;
            /** Candidates */
            candidates?: components["schemas"]["MatchCandidate"][];
            /** Flags */
            flags?: ("missing_fields" | "value_mismatch" | "unmatched" | "low_confidence_match" | "currency_changed" | "unit_mismatch" | "quantity_uncertain" | "quantity_fractional" | "cost_inferred" | "duplicate_removed" | "conflict")[];
            /** Exchange */
            exchange?: ("NASDAQ" | "NYSE" | "AMEX") | null;
            conflict?: components["schemas"]["RowConflict"] | null;
        };
        /**
         * ImportRowsBody
         * @description On-device OCR: the browser parsed the screenshot, only the stock rows are sent.
         */
        ImportRowsBody: {
            /** Rows */
            rows: components["schemas"]["ImportRowModel"][];
            /**
             * Scope
             * @default partial
             * @enum {string}
             */
            scope: "partial" | "full";
        };
        /** LaunchGateOut */
        LaunchGateOut: {
            /** Open */
            open: boolean;
            /** Reasons */
            reasons: string[];
        };
        /** LoginIn */
        LoginIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** Turnstile Token */
            turnstile_token?: string | null;
        };
        /** MarketOpen */
        MarketOpen: {
            /** Open */
            open: boolean;
        };
        /** Markets */
        Markets: {
            US: components["schemas"]["MarketOpen"];
            TASE: components["schemas"]["MarketOpen"];
            CRYPTO: components["schemas"]["MarketOpen"];
        };
        /**
         * MatchCandidate
         * @description A possible security for a row whose name match was too weak to accept automatically.
         */
        MatchCandidate: {
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Score */
            score: number;
        };
        /** MeOut */
        MeOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /**
             * Locale
             * @enum {string}
             */
            locale: "he" | "en";
            /** Disclaimer Accepted */
            disclaimer_accepted: boolean;
            /** Ocr Consent */
            ocr_consent: boolean;
            /** Csrf Token */
            csrf_token: string;
        };
        /** MissingStop */
        MissingStop: {
            /** Symbol */
            symbol: string;
            /** Reason Code */
            reason_code?: ("needs_horizon" | "stale_price" | "no_history" | "insufficient_history" | "history_price_mismatch") | null;
            /** Reason */
            reason: string;
        };
        /** Money */
        Money: {
            /** Ils */
            ils: number;
            /** Usd */
            usd: number;
        };
        /** MonthlyBar */
        MonthlyBar: {
            /** Month */
            month: string;
            /** Pnl Ils */
            pnl_ils: number;
            /** Pct */
            pct: number;
        };
        /** NotificationOut */
        NotificationOut: {
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Read */
            read: boolean;
        };
        /** PasswordBody */
        PasswordBody: {
            /** Password */
            password: string;
        };
        /** Pnl */
        Pnl: {
            /** Ils */
            ils: number;
            /** Usd */
            usd: number;
            /** Pct */
            pct: number;
        };
        /** PortfolioCreate */
        PortfolioCreate: {
            /** Name */
            name: string;
            /**
             * Base Currency
             * @default ILS
             * @enum {string}
             */
            base_currency: "ILS" | "USD";
        };
        /** PortfolioOut */
        PortfolioOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Base Currency
             * @enum {string}
             */
            base_currency: "ILS" | "USD";
            risk_filter: components["schemas"]["RiskFilterOut"];
            /** Tracking Started At */
            tracking_started_at?: string | null;
            /** Last Screenshot Update At */
            last_screenshot_update_at?: string | null;
            /**
             * Screenshot Update Stale
             * @default false
             */
            screenshot_update_stale: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PortfolioPatch */
        PortfolioPatch: {
            /** Name */
            name?: string | null;
            /** Base Currency */
            base_currency?: ("ILS" | "USD") | null;
            risk_filter?: components["schemas"]["RiskFilterIn"] | null;
        };
        /** ProposedChange */
        ProposedChange: {
            /** Row Index */
            row_index: number;
            /** Symbol */
            symbol: string | null;
            /**
             * Type
             * @enum {string}
             */
            type: "buy" | "sell" | "deposit" | "withdrawal" | "keep";
            /** Quantity */
            quantity: number | null;
            /** Amount */
            amount: number | null;
            /**
             * Currency
             * @enum {string}
             */
            currency: "ILS" | "USD";
        };
        /** ReviewRow */
        ReviewRow: {
            /** Holding Id */
            holding_id: number;
            /** Symbol */
            symbol: string;
            /** Name En */
            name_en: string;
            /** Name He */
            name_he: string;
            /** Quantity */
            quantity: number;
            /** Currency */
            currency: string;
            /** Avg Cost */
            avg_cost?: number | null;
            /** Horizon */
            horizon?: ("1w" | "1m" | "3m" | "6m" | "1y") | null;
            /** Horizon Source */
            horizon_source?: ("holding" | "override") | null;
            /**
             * Status
             * @enum {string}
             */
            status: "levels" | "needs_horizon" | "no_levels";
            /** Reason Code */
            reason_code?: ("needs_horizon" | "stale_price" | "no_history" | "insufficient_history" | "history_price_mismatch") | null;
            /** Price */
            price?: number | null;
            /** Stop Price */
            stop_price?: number | null;
            /** Stop Distance Pct */
            stop_distance_pct?: number | null;
            /** Take Profit Prices */
            take_profit_prices?: number[];
            /** Risk Ils */
            risk_ils?: number | null;
            /** Risk Usd */
            risk_usd?: number | null;
            /** Risk Pct Of Portfolio */
            risk_pct_of_portfolio?: number | null;
            /**
             * Smaller Size Needed
             * @default false
             */
            smaller_size_needed: boolean;
            /** Keep Fraction */
            keep_fraction?: number | null;
            /** Stop Fit */
            stop_fit?: ("ok" | "too_tight" | "too_wide") | null;
            levels: components["schemas"]["ExitLevelsResult"];
        };
        /** ReviewTotals */
        ReviewTotals: {
            /** Total Risk Ils */
            total_risk_ils: number;
            /** Total Risk Usd */
            total_risk_usd: number;
            /** Total Risk Pct Of Portfolio */
            total_risk_pct_of_portfolio: number;
            /** Limit Pct */
            limit_pct: number;
            /** Over Limit */
            over_limit: boolean;
            /** Positions With Stop */
            positions_with_stop: number;
            /** Top Contributors */
            top_contributors: components["schemas"]["RiskContributor"][];
            /** Positions Without Stop */
            positions_without_stop: components["schemas"]["MissingStop"][];
            /** Stops Too Tight */
            stops_too_tight: string[];
            /** Stops Too Wide */
            stops_too_wide: string[];
            /** Smaller Size Needed */
            smaller_size_needed: string[];
        };
        /** RiskContributor */
        RiskContributor: {
            /** Symbol */
            symbol: string;
            /** Risk Ils */
            risk_ils: number;
            /** Risk Pct Of Portfolio */
            risk_pct_of_portfolio: number;
            /** Share Of Total Risk Pct */
            share_of_total_risk_pct: number;
        };
        /**
         * RiskFilterIn
         * @description A risk filter as the client may send it: every field optional and bounded.
         *
         *     Percentages are in (0, 100]; `min_rr` is a ratio in (0, 100]. Presets fill the missing fields.
         */
        RiskFilterIn: {
            /** Preset */
            preset?: ("very_conservative" | "conservative" | "balanced" | "balanced_aggressive" | "aggressive" | "very_aggressive") | null;
            /** Max Position Pct */
            max_position_pct?: number | null;
            /** Max Sector Pct */
            max_sector_pct?: number | null;
            /** Max Country Pct */
            max_country_pct?: number | null;
            /** Max Loss Per Position Pct */
            max_loss_per_position_pct?: number | null;
            /** Max Portfolio Risk Per Trade Pct */
            max_portfolio_risk_per_trade_pct?: number | null;
            /** Max Total Portfolio Risk Pct */
            max_total_portfolio_risk_pct?: number | null;
            /** Min Rr */
            min_rr?: number | null;
            /** Stop Type */
            stop_type?: ("fixed" | "trailing" | "both") | null;
            /** Drawdown Defensive Pct */
            drawdown_defensive_pct?: number | null;
        };
        /** RiskFilterOut */
        RiskFilterOut: {
            /** Preset */
            preset?: string | null;
            /** Max Position Pct */
            max_position_pct: number;
            /** Max Sector Pct */
            max_sector_pct: number;
            /** Max Country Pct */
            max_country_pct: number;
            /** Max Loss Per Position Pct */
            max_loss_per_position_pct: number;
            /** Max Portfolio Risk Per Trade Pct */
            max_portfolio_risk_per_trade_pct: number;
            /** Max Total Portfolio Risk Pct */
            max_total_portfolio_risk_pct: number;
            /** Min Rr */
            min_rr: number;
            /**
             * Stop Type
             * @enum {string}
             */
            stop_type: "fixed" | "trailing" | "both";
            /** Drawdown Defensive Pct */
            drawdown_defensive_pct: number;
        };
        /**
         * RiskOverride
         * @description A per-holding override: it wins over the portfolio's filter (CLAUDE.md, product decisions).
         */
        RiskOverride: {
            /** Preset */
            preset?: ("very_conservative" | "conservative" | "balanced" | "balanced_aggressive" | "aggressive" | "very_aggressive") | null;
            /** Max Position Pct */
            max_position_pct?: number | null;
            /** Max Sector Pct */
            max_sector_pct?: number | null;
            /** Max Country Pct */
            max_country_pct?: number | null;
            /** Max Loss Per Position Pct */
            max_loss_per_position_pct?: number | null;
            /** Max Portfolio Risk Per Trade Pct */
            max_portfolio_risk_per_trade_pct?: number | null;
            /** Max Total Portfolio Risk Pct */
            max_total_portfolio_risk_pct?: number | null;
            /** Min Rr */
            min_rr?: number | null;
            /** Stop Type */
            stop_type?: ("fixed" | "trailing" | "both") | null;
            /** Drawdown Defensive Pct */
            drawdown_defensive_pct?: number | null;
        };
        /** RiskPresetOut */
        RiskPresetOut: {
            /** Preset */
            preset?: string | null;
            /** Max Position Pct */
            max_position_pct: number;
            /** Max Sector Pct */
            max_sector_pct: number;
            /** Max Country Pct */
            max_country_pct: number;
            /** Max Loss Per Position Pct */
            max_loss_per_position_pct: number;
            /** Max Portfolio Risk Per Trade Pct */
            max_portfolio_risk_per_trade_pct: number;
            /** Max Total Portfolio Risk Pct */
            max_total_portfolio_risk_pct: number;
            /** Min Rr */
            min_rr: number;
            /**
             * Stop Type
             * @enum {string}
             */
            stop_type: "fixed" | "trailing" | "both";
            /** Drawdown Defensive Pct */
            drawdown_defensive_pct: number;
            /** Name */
            name: string;
        };
        /** RiskToStop */
        RiskToStop: {
            /** Native */
            native: number;
            /** Ils */
            ils: number;
            /** Usd */
            usd: number;
            /** Pct Of Position */
            pct_of_position: number;
            /** Pct Of Portfolio */
            pct_of_portfolio?: number | null;
        };
        /**
         * RowConflict
         * @description The numbers of the copy that lost when the same card is in two screenshots with different
         *     values (the later screenshot wins). Reported so the user can see what was dropped.
         */
        RowConflict: {
            /** Price */
            price?: number | null;
            /** Value */
            value?: number | null;
            /** Quantity */
            quantity?: number | null;
        };
        /** ScaleOutStep */
        ScaleOutStep: {
            /**
             * Step
             * @enum {string}
             */
            step: "take_profit" | "trail_rest";
            /** Label */
            label: string;
            /** Price */
            price?: number | null;
            /** Fraction */
            fraction: number;
            /** Quantity */
            quantity: number;
        };
        /** ScoreCardDetail */
        ScoreCardDetail: {
            /** Holding Id */
            holding_id: number;
            /** Portfolio Id */
            portfolio_id: number;
            /** Symbol */
            symbol: string;
            /** Name En */
            name_en: string;
            /** Name He */
            name_he: string;
            /** Horizon */
            horizon?: ("1w" | "1m" | "3m" | "6m" | "1y") | null;
            /** Total */
            total: number;
            /** Confidence */
            confidence: number;
            /** Available */
            available: boolean;
            /** Validated */
            validated: boolean;
            /** Signals */
            signals: components["schemas"]["SignalBreakdownOut"][];
            explanation: components["schemas"]["Explanation"];
            /** Disclaimer */
            disclaimer: string;
        };
        /** ScoreCardMini */
        ScoreCardMini: {
            /** Total */
            total: number;
            /** Technical */
            technical: number;
            /** Patterns */
            patterns: number;
            /** Confidence */
            confidence: number;
        };
        /** SecurityHit */
        SecurityHit: {
            /** Symbol */
            symbol: string;
            /** Name En */
            name_en: string;
            /** Name He */
            name_he: string;
            /**
             * Market
             * @enum {string}
             */
            market: "US" | "TASE" | "CRYPTO";
        };
        /** SeriesPoint */
        SeriesPoint: {
            /** Date */
            date: string;
            /** Pct */
            pct: number;
            /** Sp500 Pct */
            sp500_pct?: number | null;
            /** Ta125 Pct */
            ta125_pct?: number | null;
        };
        /** SessionOut */
        SessionOut: {
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Current */
            current: boolean;
        };
        /** SignalBreakdownOut */
        SignalBreakdownOut: {
            /** Name */
            name: string;
            /** Score */
            score: number;
            /** Confidence */
            confidence: number;
            /** Weight */
            weight: number;
            /** Nominal Weight */
            nominal_weight?: number | null;
            /** Reasons */
            reasons: string[];
            /** Data As Of */
            data_as_of: string;
            explanation: components["schemas"]["Explanation"];
        };
        /**
         * SignalContribution
         * @description One signal's part in a combined score: what it said and how much it counted.
         */
        SignalContribution: {
            /** Name */
            name: string;
            /** Score */
            score: number;
            /** Weight */
            weight: number;
            /** Confidence */
            confidence: number;
            /** Raw */
            raw?: {
                [key: string]: number | string | null;
            };
        };
        /** SignupIn */
        SignupIn: {
            /** Invite Code */
            invite_code: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Accept Disclaimer */
            accept_disclaimer: boolean;
            /**
             * Locale
             * @default he
             * @enum {string}
             */
            locale: "he" | "en";
        };
        /**
         * SizeGuidance
         * @description The stop stays where the chart puts it; this is how many shares fit the risk filter.
         */
        SizeGuidance: {
            /** Needed */
            needed: boolean;
            /** Keep Fraction */
            keep_fraction: number;
            /** Current Quantity */
            current_quantity: number;
            /** Suggested Quantity */
            suggested_quantity: number;
            /** Rules */
            rules: string[];
            /** Reason */
            reason: string;
        };
        /** SkippedSource */
        SkippedSource: {
            /** Source */
            source: string;
            /** Reason */
            reason: string;
        };
        /** StopCandidate */
        StopCandidate: {
            /**
             * Source
             * @enum {string}
             */
            source: "atr" | "structure" | "moving_average" | "max_loss" | "saved_stop" | "trailing";
            /** Price */
            price: number;
            /** Distance Pct */
            distance_pct: number;
            /**
             * Chosen
             * @default false
             */
            chosen: boolean;
            /** Note */
            note: string;
        };
        /**
         * StopState
         * @description What a trailing stop remembers between runs: the highest high seen and the stop so far.
         */
        StopState: {
            /** Highest High */
            highest_high?: number | null;
            /** Stop */
            stop?: number | null;
        };
        /** SummaryOut */
        SummaryOut: {
            value: components["schemas"]["Money"];
            day_pnl: components["schemas"]["Pnl"];
            week_pnl: components["schemas"]["Pnl"];
            month_pnl: components["schemas"]["Pnl"];
            since_start_pnl: components["schemas"]["Pnl"];
            /** Since Start Date */
            since_start_date?: string | null;
            /** Last Screenshot Update At */
            last_screenshot_update_at?: string | null;
            /**
             * Screenshot Update Stale
             * @default false
             */
            screenshot_update_stale: boolean;
            /**
             * Week Start
             * Format: date
             */
            week_start: string;
            /** Fx Stale */
            fx_stale: boolean;
            /** Fx Source */
            fx_source?: string | null;
            /**
             * Fx Basis
             * @default live
             * @enum {string}
             */
            fx_basis: "live" | "last_close";
            /** Fx As Of */
            fx_as_of?: string | null;
            /**
             * Price Sources
             * @default []
             */
            price_sources: string[];
            /** Weekly Bars */
            weekly_bars: components["schemas"]["WeeklyBar"][];
            /** Monthly Bars */
            monthly_bars: components["schemas"]["MonthlyBar"][];
            /** Since Start Series */
            since_start_series: components["schemas"]["SeriesPoint"][];
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            markets: components["schemas"]["Markets"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WeeklyBar */
        WeeklyBar: {
            /**
             * Week Start
             * Format: date
             */
            week_start: string;
            /** Pnl Ils */
            pnl_ils: number;
            /** Pct */
            pct: number;
        };
        /** XrayOut */
        XrayOut: {
            /** Concentration */
            concentration: {
                [key: string]: unknown;
            }[];
            /** Currency Exposure */
            currency_exposure: components["schemas"]["ExposureItem"][];
            /** Country Exposure */
            country_exposure: components["schemas"]["ExposureItem"][];
            /** Sector Exposure */
            sector_exposure: components["schemas"]["ExposureItem"][];
            /** Home Bias */
            home_bias: {
                [key: string]: unknown;
            };
            /** Breaches */
            breaches: components["schemas"]["Breach"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signup_api_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description A Cloudflare Turnstile token is required (`code: turnstile_required`). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeRequiredOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    consent_ocr_api_auth_consent_ocr_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    export_me_api_me_export_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_me_api_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_auth_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"][];
                };
            };
        };
    };
    revoke_session_api_auth_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_all_sessions_api_auth_sessions_revoke_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_portfolios_api_portfolios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioOut"][];
                };
            };
        };
    };
    create_portfolio_api_portfolios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    combined_summary_api_portfolios_combined_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryOut"];
                };
            };
        };
    };
    get_one_api_portfolios__portfolio_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_portfolio_api_portfolios__portfolio_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_portfolio_api_portfolios__portfolio_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_api_portfolios__portfolio_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    holdings_api_portfolios__portfolio_id__holdings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_holding_api_portfolios__portfolio_id__holdings_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    xray_api_portfolios__portfolio_id__xray_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["XrayOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    heatmap_api_portfolios__portfolio_id__heatmap_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeatmapItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_holding_api_portfolios__portfolio_id__holdings__holding_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
                holding_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_holding_api_portfolios__portfolio_id__holdings__holding_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
                holding_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldingPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_import_api_portfolios__portfolio_id__imports_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        /** @description The raw image bytes (not multipart). */
        requestBody: {
            content: {
                "image/png": string;
                "image/jpeg": string;
                "image/webp": string;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportDraftOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_import_from_rows_api_portfolios__portfolio_id__imports_rows_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRowsBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportDraftOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_import_api_imports__draft_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportDraftOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_import_api_imports__draft_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportDraftOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_import_api_imports__draft_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportDraftOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    launch_gate_api_launch_gate_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LaunchGateOut"];
                };
            };
        };
    };
    risk_presets_api_risk_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskPresetOut"][];
                };
            };
        };
    };
    securities_search_api_securities_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecurityHit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scorecard_api_holdings__holding_id__scorecard_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                holding_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreCardDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alerts_api_alerts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"][];
                };
            };
        };
    };
    create_alert_api_alerts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_alert_api_alerts__alert_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    notifications_api_notifications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationOut"][];
                };
            };
        };
    };
    read_notification_api_notifications__notification_id__read_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    holding_exit_levels_api_holdings__holding_id__exit_levels_get: {
        parameters: {
            query?: {
                horizon?: ("1w" | "1m" | "3m" | "6m" | "1y") | null;
                risk?: ("very_conservative" | "conservative" | "balanced" | "balanced_aggressive" | "aggressive" | "very_aggressive") | null;
                prior_stop?: number | null;
                analyst_mean?: number | null;
                analyst_high?: number | null;
            };
            header?: never;
            path: {
                holding_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExitLevelsResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    exit_review_api_portfolios__portfolio_id__exit_review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExitReviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExitReviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
}
